In [1]:
import numpy as np
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [2]:
a.shape

(3, 3, 3)

In [3]:
a.shape = (3,9)   #This fucntion is in memory
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

# If any function makes changes to the original data in the memory,it is called In memory function

In [5]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
c= np.ones_like(a)
c

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
np.empty((2,2))

array([[4.9406565e-324, 1.1683036e-311],
       [0.0000000e+000, 1.0609979e-314]])

In [12]:
np.empty_like(a)

array([[-1883268112,         550,   394805792,  1622561866, -1727174224,
                550, -1881786208,         550,  1943731263],
       [-2010157851, -1727173840,         550, -1881760512,         550,
         -424060985,  -468475765, -1727176400,         550],
       [-1881728864,         550,  -656899756,   845202382, -1727179408,
                550, -1881649616,         550,  -638343203]])

In [14]:
np.full((2,2,2),fill_value=5,dtype='float32')

array([[[5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.]]], dtype=float32)

In [16]:
np.eye(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
np.eye??

In [18]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
x = np.arange(1,13).reshape((3,4)).astype(np.float64)
x
%time

Wall time: 0 ns


In [26]:
y = np.arange(1,13,dtype='int32').reshape((3,4))
y
%time

Wall time: 0 ns


In [27]:
type(y)

numpy.ndarray

In [29]:
f = np.array([1,2,3],dtype='i8')
print(f.dtype)

int64


In [31]:
t = np.arange(1,28).reshape((3,3,3))
t

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# Boolean array in numpy

In [32]:
t % 5 == 0

array([[[False, False, False],
        [False,  True, False],
        [False, False, False]],

       [[ True, False, False],
        [False, False,  True],
        [False, False, False]],

       [[False,  True, False],
        [False, False, False],
        [ True, False, False]]])

In [33]:
a[a%5==0]

array([ 5, 10, 15, 20, 25])

In [34]:
a[(a%5==0)&(a%3==0)]

array([15])

In [35]:
print('Haven\'t worked in so many days!')

Haven't worked in so many days!


In [39]:
a = np.array([1,2,3,4])
b = a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

# April 26th,2020

In [45]:
import numpy as np
a = np.zeros((8,4))
for i in range(len(a)):
    a[i] = i
a

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [55]:
a[[-1,-2,-3]][:,[-1,0]]

array([[7., 7.],
       [6., 6.],
       [5., 5.]])

In [58]:
print(a.T)
print()
print(a.transpose())

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]]

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]]


In [68]:
import numpy as np
x = np.array([[1,2],
             [3,4]])
y = np.array([[5,6],
              [7,8]])
print(x)
print()
print(y)
print()
#Element wise multiplication(mulitpying corresponding elements)
print(x * y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]


In [71]:
#Dot product  --The one used in linear algebra
print(x @ y)
#and also,This is another method
print(x.dot(y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [73]:
#An easy way to generate a multidimensional matrix
arr = np.arange(2*2*4).reshape(2,2,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [ ]:
##Have to check transpose in numpy videos on youtube

In [86]:
import numpy as np
data = np.random.randn(2,3)
data * 10
print(data + data)

[[-1.43998354 -2.49690425 -0.38444681]
 [ 2.21159162  4.24160557  0.60541528]]


In [81]:
data1 = np.empty((2,2))
data1

array([[2048.00049305, 2048.00049305],
       [2048.00049305, 2048.00049305]])

In [83]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
data2 = np.ones_like(data,dtype='int')
data2

array([[1, 1, 1],
       [1, 1, 1]])

In [90]:
np.full??

In [93]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])