In [5]:
import numpy as np
a = np.random.randint(1,11,size = 11)
b =np.random.randint(1,5,size=5)

In [4]:
a

array([5, 1, 3, 6, 8, 9, 1, 2, 7, 2, 3])

In [6]:
b

array([1, 3, 2, 3, 3])

In [9]:
lst = [True if x in a else False for x in b] #using regular python
lst

[False, True, True, True, True]

In [10]:
np.in1d(b,a) #using numpy

array([False,  True,  True,  True,  True])

# Stacking

In [15]:
a = np.arange(1,11)
a
b = a * 3
b

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [17]:
np.stack((a,b),axis = 0) #stacking the arrays in one array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [18]:
np.stack((a,b),axis= 1)

array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [19]:
np.hstack((a,b)) #combines the two arrays into one

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  6,  9, 12, 15, 18, 21,
       24, 27, 30])

In [20]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [22]:
a = np.arange(2*2*2).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
b = a + 10

In [24]:
b

array([[[ 0,  3],
        [ 6,  9]],

       [[12, 15],
        [18, 21]]])

In [26]:
np.dstack((a,b))

array([[[ 0,  1, 10, 11],
        [ 2,  3, 12, 13]],

       [[ 4,  5, 14, 15],
        [ 6,  7, 16, 17]]])

In [ ]:
#In braodcasting numpy generates an array of the same size and then performs the computation 

In [30]:
a = np.arange(1,11)
a
b = a * 3
print(np.column_stack((a,b)))
print(np.row_stack((a,b)))

[[ 1  3]
 [ 2  6]
 [ 3  9]
 [ 4 12]
 [ 5 15]
 [ 6 18]
 [ 7 21]
 [ 8 24]
 [ 9 27]
 [10 30]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 3  6  9 12 15 18 21 24 27 30]]


In [32]:
a = np.arange(6*5).reshape(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [37]:
x,y,z = np.split(a,3)
print(x)
print()
print(y)
print()
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]]

[[20 21 22 23 24]
 [25 26 27 28 29]]


In [38]:
np.intersect1d(a,b)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
np.union1d(a,b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [40]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [41]:
b

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [42]:
t = np.random.randint(1,21,size=20)
h = np.random.randint(1,11,size = 10)
print(t,h,sep='\n\n')

[ 2  2 19  6  6  5  8  9  6 19  8  2 13  4 20 15  2 17  9 16]

[ 4  1  3  2 10  3 10  8  6  8]


In [43]:
np.setdiff1d(t,h) #looking for elements that are in t but not in h

array([ 5,  9, 13, 15, 16, 17, 19, 20])

In [45]:
np.setxor1d(t,h)  #Looking for elements that are both unique to t and h

array([ 1,  3,  5,  9, 10, 13, 15, 16, 17, 19, 20])

# Pandas

In [ ]:
#Data can be loaded into chunks if it's large...
#used for data analytics,used for analysing tabular data,in the form of rows and columns
#Tasks can be automated!
#encoding = 'cp1252' to avoid any errors
#One column in a table is a series
#The entire table is called Dataframe
#One Dataframe is composed of multiple series

In [51]:
import pandas as pd
df = pd.read_html('https://www.w3schools.com/howto/howto_google_fonts.asp')
df[0]

ValueError: No tables found

In [54]:
import pandas as pd
df = pd.read_html('https://www.w3schools.com/html/html_tables.asp')
df[1]

Tag                                        Description
0     <table>                                    Defines a table
1        <th>                   Defines a header cell in a table
2        <tr>                           Defines a row in a table
3        <td>                          Defines a cell in a table
4   <caption>                            Defines a table caption
5  <colgroup>  Specifies a group of one or more columns in a ...
6       <col>  Specifies column properties for each column wi...
7     <thead>               Groups the header content in a table
8     <tbody>                 Groups the body content in a table
9     <tfoot>               Groups the footer content in a table

In [57]:
date_range = pd.date_range('2020-01-01','2020-05-03',freq='M')
date_range

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30'], dtype='datetime64[ns]', freq='M')

In [67]:
import numpy as np
import pandas as pd
df = pd.read_excel('train.csv')
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'