In [1]:
#Exercise 1 
import numpy as np
np.__version__

'1.18.2'

In [2]:
#Exercise 2
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Exercise 3
np.ones((3,3),dtype='bool')
#Alternative method
np.full((3,3),True,dtype='bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
#Exercise 4 : Extraction of odd numbers
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 != 0]

array([1, 3, 5, 7, 9])

In [14]:
#Exercise 5: Replacing values with another value
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [27]:
#Exerxise 6 : Replacement without modification
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1 =arr.copy()
arr1[arr1 % 2 != 0] = -1
print(arr,arr1,sep='\n\n')
#Alternative
out = np.where(arr%2!=0,-1,arr)
out

[0 1 2 3 4 5 6 7 8 9]

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [33]:
#Exercise 7 :Reshaping an array
arr = np.arange(10).reshape(2,5) #.reshape(2,-1) -1 lets numpy decides the number of columns automatically
#This works for both rows and columns
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
#Exercise 8 : Vertical Stacking
a = np.arange(10).reshape(2,-1)
a
b = np.repeat(1,10).reshape(2,-1)
b
np.vstack((a,b))  # Method 1
np.concatenate((a,b),axis = 0) #Method 2
np.r_[a,b] ###########Method 3


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
#Exercise 9 : Horizontal Stacking
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.hstack((a,b))  #Method 1
np.concatenate((a,b),axis = 1) #Method 2
np.c_[a,b]   ##################Method 3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [77]:
#Exercise 10 : Creating custom sequences without hardcoding
a = np.array([1,2,3]*3) 
arr = np.repeat(a[0:3],3)
arr
np.hstack((arr,a))
#np.hstack((np.repeat(a[0:],3),np.repeat(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [81]:
#Saner solution to exercise 10
a = np.array([1,2,3])
a
np.tile(a,3)
np.repeat(a,3)
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [83]:
#Exercise 11 : Finding common elements between two arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [94]:
#Exercise 12: removing common items from one array
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
#c = np.intersect1d(a,b)
#np.delete(a,np.where(a==c))
#----------------Easier Way------------------ 
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [98]:
#Exercise 13 : Finding the index of matching elements in numpy
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.where(a == b)
result

(array([1, 3, 5, 7], dtype=int64),)

In [112]:
#Exerxise 14: Extracting the numbers from a specific range from an array
a = np.array([2, 6, 1, 9, 10, 3, 27])
#------------Method 1------------------
index = np.where((a >= 5) & (a <= 10))
a[index]

#------------Method 2-----------------
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

#-------------Method 3-----------------
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [133]:
#Exercise 15 :  Python functions

def maxx(x,y):
    if x >= y:
        return x
    else:
        return y
    
'''
def pair_maxx(a,b):
    for i in range(len(a)):
        if a[i] > b[i]:
             print(a[i])
        else:
            print(b[i])
pair_maxx(a,b)

'''
pair_max = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a,b)
#-------------Sequence------------
#1.Function to be used
#2.Vectorisation of the function
#3.The arrays you need to apply the function on
#4.Application of the function on the arrays

array([6., 7., 9., 8., 9., 7., 5.])

In [137]:
#Exercise 16 : swapping columns
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[0,1]] = arr[:,[1,0]]
print()
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [138]:
#Exercise 17 : swapping rows
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[0,1],:] = arr[[1,0],:]
print()
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [146]:
#Exercise 18: Revesring the rows of a 2D array
arr = np.arange(9).reshape(3,3)
print(np.fliplr(arr)) #Flips the content of each row
print()
print(np.flipud(arr))  #Flips the rows of an nd matrix
print()
print(arr)


[[2 1 0]
 [5 4 3]
 [8 7 6]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [154]:
#Continuation of Exercise 18
a = np.arange(1,16).reshape(5,-1)
print(a)
print()
print(a[::-1,:])  #Row reversal
print()
print(a[:,::-1])  #Column reversal

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[13 14 15]
 [10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]
 [15 14 13]]


In [150]:
#Exercise 19 : Reversing the columns of a 2D array
arr = np.arange(9).reshape(3,3)
print(arr)
print()
print(np.fliplr(arr)) #Column flip

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [184]:
#Exercise 20 : Creating a 2D array of random floats between 5 & 10
import random
sampl = np.random.uniform(low=5.0, high=10.0, size=(5,3)) #Function to generate random float values within a specific range
print(sampl)
#------------------------Second Solution----------------
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
#I think they are first generating random integers and then adding float values between 0 & 1
print()
print(rand_arr)

[[6.92470486 6.26781811 9.52348328]
 [8.69735596 7.73267148 7.50239305]
 [6.28138018 7.0530907  6.24765448]
 [6.40565221 7.32740865 6.42642824]
 [5.90120125 6.67493372 8.58977926]]

[[9.86179574 5.23138235 9.71297041]
 [6.50301218 9.53904387 7.93367098]
 [5.44505763 6.64807109 7.5542665 ]
 [9.51268464 9.30741284 5.26356101]
 [5.24084079 5.47048989 9.34027619]]


In [187]:
#Exercise 21: printing floats upto 3 decimal points
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr)

[[0.85  0.149 0.374]
 [0.76  0.486 0.564]
 [0.18  0.221 0.342]
 [0.678 0.176 0.859]
 [0.86  0.882 0.933]]


In [191]:
#Exercise 22: Supressing the exponents
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.   , 0.   , 0.001],
       [0.   , 0.001, 0.001],
       [0.   , 0.001, 0.   ]])

In [193]:
#Exercise 25 : Importing numbers and data in numpy 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [195]:
data = np.random.randint(low=1, high=11, size=(9,9))
data

array([[ 3,  2,  7,  4, 10,  3,  9,  9,  7],
       [10,  8,  1, 10,  1,  6,  1,  9,  8],
       [ 9,  1,  2,  9,  3, 10,  5,  5,  7],
       [ 2,  1,  7,  8,  7,  8,  3,  5,  6],
       [ 2, 10,  8,  3,  7,  9, 10,  4,  3],
       [ 9,  1,  2,  9, 10, 10,  5,  5,  8],
       [ 4,  7,  9,  6,  5,  2,  8,  7,  5],
       [ 7, 10,  3,  4, 10, 10,  1,  5,  8],
       [ 6,  5, 10,  9,  2,  9,  5,  3, 10]])

In [206]:
#filename = 'Desktop\WORK\data.txt'

data1 = np.genfromtxt('Desktop/WORK/Dummies.csv',delimiter=',')
print(data1)

[[    nan     nan     nan]
 [1714.      2.4      nan]
 [1664.      2.52     nan]
 [1760.      2.54     nan]
 [1685.      2.74     nan]
 [1693.      2.83     nan]
 [1670.      2.91     nan]
 [1764.      3.       nan]
 [1764.      3.       nan]
 [1792.      3.01     nan]
 [1850.      3.01     nan]
 [1735.      3.02     nan]
 [1775.      3.07     nan]
 [1735.      3.08     nan]
 [1712.      3.08     nan]
 [1773.      3.12     nan]
 [1872.      3.17     nan]
 [1755.      3.17     nan]
 [1674.      3.17     nan]
 [1842.      3.17     nan]
 [1786.      3.19     nan]
 [1761.      3.19     nan]
 [1722.      3.19     nan]
 [1663.      3.2      nan]
 [1687.      3.21     nan]
 [1974.      3.24     nan]
 [1826.      3.28     nan]
 [1787.      3.28     nan]
 [1821.      3.28     nan]
 [2020.      3.28     nan]
 [1794.      3.28     nan]
 [1769.      3.28     nan]
 [1934.      3.28     nan]
 [1775.      3.29     nan]
 [1855.      3.29     nan]
 [1880.      3.29     nan]
 [1849.      3.31     nan]
 